---
authors:
  - chouseknecht (https://github.com/chouseknecht)
  - geerlingguy (https://www.jeffgeerling.com/)
  - maxamillion (https://github.com/maxamillion)
  - jmontleon (https://github.com/jmontleon)
  - fabianvf (https://github.com/fabianvf)
  - willthames (https://github.com/willthames)
  - mmazur (https://github.com/mmazur)
  - jamescassell (https://github.com/jamescassell)
dependencies:
  cloud.common: '*'
  kubernetes.core: '>=2.0.0'
description: Kubernetes Collection for Ansible.
documentation: ''
homepage: ''
issues: https://github.com/ansible-collections/community.kubernetes/issues
license_file: LICENSE
name: kubernetes
namespace: community
readme: README.md
repository: https://github.com/ansible-collections/community.kubernetes
tags:
  - kubernetes
  - k8s
  - cloud
  - infrastructure
  - openshift
  - okd
  - cluster
version: 1.2.0
build_ignore:
  - .DS_Store
  - '*.tar.gz'
