---
- name: Create a SelfSubjectAccessReview resource
  register: can_i_create_namespaces
  ignore_errors: yes
  k8s:
    state: present
    definition:
      apiVersion: authorization.k8s.io/v1
      kind: SelfSubjectAccessReview
      spec:
        resourceAttributes:
          group: v1
          resource: Namespace
          verb: create

- name: Assert that the SelfSubjectAccessReview request succeded
  assert:
    that:
      - can_i_create_namespaces is successful
      - (can_i_create_namespaces.resources | length) == 1
      - can_i_create_namespaces.resources.0.status is defined
      - can_i_create_namespaces.resources.0.status.allowed is defined
      - can_i_create_namespaces.resources.0.status.allowed
