---
driver:
  name: delegated
  options:
    managed: false
    login_cmd_template: 'docker exec -ti {instance} bash'
    ansible_connection_options:
      ansible_connection: docker
lint: |
  set -e
  yamllint .
  flake8
platforms:
  - name: instance-kind
provisioner:
  name: ansible
  log: true
  config_options:
    inventory:
      enable_plugins: community.kubernetes.k8s
  lint: {}
  inventory:
    hosts:
      plugin: community.kubernetes.k8s
    host_vars:
      localhost:
        ansible_python_interpreter: '{{ ansible_playbook_python }}'
  env:
    ANSIBLE_FORCE_COLOR: 'true'
  options:
    vvv: True
scenario:
  name: default
  test_sequence:
    - lint
    - syntax
    - converge
    - verify
