name: 'Repo Lockdown'

on:
  issues:
    types: opened
  pull_request_target:
    types: opened

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          exclude-pr-labels: 'keep'
          exclude-issue-labels: 'keep'
          issue-labels: 'repo-lockdown'
          pr-labels: 'repo-lockdown'
          pr-comment: >
            This repository does not accept pull requests,
            see the README for details.
